[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["cd backend && pip install -r requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "cd backend && gunicorn -c gunicorn.conf.py app.main:app"
