[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.virtualenv"]

[phases.install]
cmds = [
    "python -m venv /opt/venv",
    "/opt/venv/bin/pip install --upgrade pip",
    "cd backend && /opt/venv/bin/pip install -r requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = "cd backend && /opt/venv/bin/gunicorn -c gunicorn.conf.py app.main:app"
